services:
  db:
    build: ./postgres
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-42:
    build: ./auth-42
    container_name: auth-42
    env_file:
      - auth-42/.env
    volumes:
      - ./certs:/certs
    ports:
      - "8442:8442"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  auth-local:
    build: ./auth-local
    container_name: auth-local
    env_file:
      - auth-local/.env
    volumes:
      - ./certs:/certs
    ports:
      - "8441:8441"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: apache-web
    volumes:
      - ./certs:/etc/ssl/certs
      - apache_logs:/var/log/apache2
    ports:
      - "8443:443"
    depends_on:
      auth-42:
        condition: service_started
      auth-local:
        condition: service_started
    networks:
      - app_network

  prometheus:
    build: ./monitoring/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app_network

  grafana:
    build: ./monitoring/grafana
    container_name: grafana
    env_file:
      - ./monitoring/grafana/.env
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - app_network

volumes:
  postgres_data:
  grafana_data:
  prometheus_data:
  apache_logs:

networks:
  app_network:
    driver: bridge
