DROP DATABASE IF EXISTS postgres_42;
CREATE DATABASE postgres_42;

\c postgres_42

DROP SCHEMA IF EXISTS backend42 CASCADE;
CREATE SCHEMA backend42;

DROP SCHEMA IF EXISTS backend2 CASCADE;
CREATE SCHEMA backend2;
